version: '3.8'

# IMPORTANT FOR SECURITY !!! while I develop my app, these values are hardcoded for simplicity’s sake,
#               if you pull this repo and want to use the app in a secure way, do the following:
# 1. create .txt files for docker secrets (name the files like mysql_root_password.txt etc.)
# 2. run the command `docker swarm init`
# 3. create the docker secret by calling commands like `docker secret create mysql_root_password mysql_root_password.txt`
# 4. add above the `environment:` the following:
#     secrets:
#       - mysql_root_password
#       - etc.
# 5. replace the below env as MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql_root_password
# 6. then deploy `docker stack deploy -c docker-compose.yml my_stack`

services:
  database:
    image: mysql:latest
    restart: always
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: financemanagement
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3

  backend:
    image: dockerfile-backend
    ports:
      - "8080:8080"
    depends_on:
      - database
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://localhost:3306/financemanagement
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    command: ["sh", "-c", "./wait-for-it.sh database:3306 -- java -jar app.jar"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 3
    volumes:
      - backend-data:/app/data
volumes:
  mysql-data:
  backend-data: