# Dockerfile-backend
FROM openjdk:21-jdk-slim

LABEL maintainer="oblivionLi (Liviu G. Andrei = liviuandrei.dev@gmail.com)"

VOLUME /tmp

WORKDIR /app

COPY gradlew .
COPY gradle gradle
COPY build.gradle settings.gradle ./
COPY src src

ADD https://raw.githubusercontent.com/vishnubob/wait-for-it/master/wait-for-it.sh /wait-for-it.sh

RUN chmod +x /wait-for-it.sh
RUN chmod +x gradlew

RUN ./gradlew --no-daemon build

# RUN ./gradlew --no-daemon build --info

COPY build/libs/*.jar app.jar
COPY src/main/resources/application.properties src/main/resources/application.properties
COPY src/main/resources/application-test.properties src/main/resources/application-test.properties

EXPOSE 8080

ENTRYPOINT ["java", "-jar", "app.jar"]