# Use an official OpenJDK runtime as a parent image
FROM openjdk:21-jdk-slim

# Set the maintainer label
LABEL maintainer="oblivionLi (Liviu G. Andrei = liviuandrei.dev@gmail.com)"

# Set the working directory in the container
WORKDIR /app

# Copy the Gradle wrapper and the Gradle build files
COPY gradlew .
COPY gradle gradle
COPY build.gradle settings.gradle ./

# Copy the source code
COPY src src

# Accept build arguments
ARG SPRING_DATASOURCE_URL
ARG SPRING_DATASOURCE_USERNAME
ARG SPRING_DATASOURCE_PASSWORD
ARG SECURITY_JWT_TOKEN_SECRET_KEY
ARG SPRING_MAIL_HOST
ARG SPRING_MAIL_PORT
ARG SPRING_MAIL_USERNAME
ARG SPRING_MAIL_PASSWORD
ARG SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH
ARG SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE
ARG SPRING_MAIL_PROPERTIES_MAIL_DEBUG

# Create the .env file
RUN echo "SPRING_DATASOURCE_URL=$SPRING_DATASOURCE_URL" >> .env \
    && echo "SPRING_DATASOURCE_USERNAME=$SPRING_DATASOURCE_USERNAME" >> .env \
    && echo "SPRING_DATASOURCE_PASSWORD=$SPRING_DATASOURCE_PASSWORD" >> .env \
    && echo "SECURITY_JWT_TOKEN_SECRET_KEY=$SECURITY_JWT_TOKEN_SECRET_KEY" >> .env \
    && echo "SPRING_MAIL_HOST=$SPRING_MAIL_HOST" >> .env \
    && echo "SPRING_MAIL_PORT=$SPRING_MAIL_PORT" >> .env \
    && echo "SPRING_MAIL_USERNAME=$SPRING_MAIL_USERNAME" >> .env \
    && echo "SPRING_MAIL_PASSWORD=$SPRING_MAIL_PASSWORD" >> .env \
    && echo "SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH=$SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH" >> .env \
    && echo "SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE=$SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE" >> .env \
    && echo "SPRING_MAIL_PROPERTIES_MAIL_DEBUG=$SPRING_MAIL_PROPERTIES_MAIL_DEBUG" >> .env


# Build the application using Gradle
RUN ./gradlew --no-daemon build -x test

# Copy the built JAR file to the container
COPY build/libs/*.jar app.jar

# Expose the application port
EXPOSE 8080

# Define the entry point for the container
ENTRYPOINT ["java", "-jar", "app.jar"]
