# Dockerfile-frontend
FROM node:16-alpine

MAINTAINER oblivionLi (Liviu G. Andrei = liviuandrei.dev@gmail.com)

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

RUN npm run build

EXPOSE 3000

CMD ["npm", "run", "start"]