# Stage 1: Build the React app
FROM node:16-alpine as build

LABEL maintainer="oblivionLi (Liviu G. Andrei = liviuandrei.dev@gmail.com)"

WORKDIR /app

COPY package.json package-lock.json ./

RUN npm install

COPY . .

RUN npm run build

# Stage 2: Serve the React app with Nginx
FROM nginx:alpine

COPY --from=build /app/build /usr/share/nginx/html

COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]