# main.yaml
name: Java CI with Gradle

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'adopt'

      - name: Grant execute permission for Gradle wrapper
        run: chmod +x ./gradlew

      - name: Set environment variables
        run: |
          echo "SPRING_PROFILES_ACTIVE=test" >> $GITHUB_ENV

      - name: Build with Gradle
        run: ./gradlew clean build --info

#      - name: Upload test results
#        if: failure()
#        uses: actions/upload-artifact@v2
#        with:
#          name: test-results
#          path: build/reports/tests/test

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build backend Docker image
        run: docker build -t backend -f Dockerfile-backend .

      - name: Build frontend Docker image
        run: docker build -t frontend -f frontend-react/Dockerfile-frontend frontend-react